### ISSUE TITLE
Baseline Command Error? Scrapy version?

### ISSUE THREAD

**Issue by brycecf** [Data4Democracy/media-crawler#17]
`scrapy crawl media_spider -a media_url="https://www.washingtonpost.com/news/post-politics/wp/2017/09/07/did-facebook-ads-traced-to-a-russian-company-violate-u-s-election-law/?tid=a_inl&utm_term=.e24142917aa8" max_depth=5 -o media.json`

Is this command still working?  Which version of Scrapy is this project using?

I have the following error:
`crawl: error: running 'scrapy crawl' with more than one spider is no longer supported`

**Comment by josephpd3** [comment]
Hey @brycecf ! I am sorry it took me so long, but after testing out the command some more I noticed a bug I had to fix in the depth control. In the original there was a typo where you had to specify each argument with `-a`, and I forgot to add that into the documented command.

I made some changes so that depth will no longer be specified via the command line (the inner workings of which were breaking the crawler), but instead in the `settings.py` file. You should be able to make a pull request from the updated master branch here to yours and then pull down your master branch to get the update.

After that, try out: `scrapy crawl media_spider -o media.json -a media_url="https://www.washingtonpost.com/news/post-politics/wp/2017/09/07/did-facebook-ads-traced-to-a-russian-company-violate-u-s-election-law/?tid=a_inl&utm_term=.e24142917aa8"`

It should run fine now. Please let me know if you have further issues.

**Comment by brycecf** [comment]
@josephpd3 Thanks! It's working now.
